### PR TITLE
CI: Add Github workflow

### LINKED ISSUE #3: pthread.h not found on Windows (using MSVC)
When running `cargo build` on Windows using MSVC (via Github Actions), I'm getting this error:

```
  running: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX64\\x64\\cl.exe" "/nologo" "/MD" "/Z7" "/I" "D:\\a\\vorbis-sys\\vorbis-sys\\libvorbis\\include" "/I" "D:\\a\\vorbis-sys\\vorbis-sys\\libvorbis\\lib" "/I" "C:\\Users\\runneradmin\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\ogg-sys-0.0.9\\libogg\\include" "/D_USRDLL" "/DLIBVORBIS_EXPORTS" "/W4" "/FoD:\\a\\vorbis-sys\\vorbis-sys\\target\\debug\\build\\vorbis-sys-474051d343568d5d\\out\\libvorbis/lib/misc.o" "/c" "libvorbis/lib/misc.c"
  misc.c
  libvorbis/lib/misc.c(14): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory
  exit code: 2
```

### PR DESCRIPTION
**Pull request by mgeier**
~I've disabled MSVC because of #3.~ UPDATE: fixes #3.

The passing test can be seen at https://github.com/mgeier/vorbis-sys/actions/runs/247828549.

### CODE REVIEW

**Comment by mgeier** [comment]
I've tried a ton of stuff to get it to compile with MSVC ... finally I found out that I can simply remove a source file and everything is honky-dory: 1464bd1707b51f66e0279040b18085f25f675033

Now MSVC can be activated as well: ac7feb718dd1d1c8e3ed71dc12a7ba44ffd61289

The passing test can be seen at https://github.com/mgeier/vorbis-sys/actions/runs/252551211.

**Comment by mgeier** [comment]
@tomaka ping?

**Comment by mgeier** [comment]
@tomaka Can you please review/merge this?

If you don't want the Github workflow for some reason, please let me know, then I can propose the bugfix in 1464bd1707b51f66e0279040b18085f25f675033 as a separate PR.

**Comment by tomaka** [comment]
Sorry, you fell in second page of my GitHub notifications :grimacing: 
I'm not really maintaining `vorbis-sys` and `ogg-sys` anymore.

**Comment by mgeier** [comment]
No problem, thanks for merging!

> I'm not really maintaining `vorbis-sys` and `ogg-sys` anymore.

Are you still willing to merge the occasional PR and make the occasional release?

Or would you like to transfer maintainership?

The problem with `*-sys` crates is that there should ideally be only one for each library, right?

I already was kinda forced to create [libflac-sys](https://crates.io/crates/libflac-sys), because [flac-sys](https://crates.io/crates/flac-sys) seems to be abandoned (I got no response to my issue https://github.com/AustinJ235/flac-sys/issues/1).

I would like to avoid doing the same thing for `vorbis-sys`!

**Comment by tomaka** [comment]
Considering that there's been 3 PRs in two years so far, that should be manageable.

**Comment by mgeier** [comment]
That sounds good. I might make a few more of those, e.g. #7.

**Pull request merged**
